CNM viewer for settler
dguenms/Dawn-of-Civilization pull request #148
Opened 2017-02-28 15:46 UTC by MeuhV1

2017-03-10 13:21 UTC, MeuhV1 commented
The Mayan contact UHV now loops over less plots (should be faster)
The IsConnectedByRailroad first checks if at least one of the plots in the target list is connected by railroad. If not, the heap calculations can (and now will) be skipped because they would always return False.

2017-03-11 22:18 UTC, dguenms commented
Got this in Dutch 600 AD autoplay:
```Traceback (most recent call last):
  File "BugEventManager", line 400, in _handleDefaultEvent
  File "CvRFCEventHandler", line 578, in onBeginGameTurn
  File "RiseAndFall", line 834, in checkTurn
  File "RiseAndFall", line 880, in rebirthFirstTurn
  File "RFCUtils", line 1080, in isFree
TypeError: unpack non-sequence```

2017-03-12 18:38 UTC, MeuhV1 commented
Fixed

2017-03-12 22:32 UTC, dguenms commented
Thanks, will give it another look.

2017-03-13 14:00 UTC, dguenms requested changes
Only two minor changes.

2017-03-13 14:00 UTC, dguenms commented on Assets/Python/RFCUtils.py
> +				if plot.getImprovementType() == iPlantation:
You mixed the plantations here, slave plantations are supposed to be converted to regular plantations.

2017-03-13 14:00 UTC, dguenms commented on Assets/Python/RFCUtils.py
> +		return [i for i in range(iBeginWonders, iNumBuildings)]
I prefer the implementation using `isWorldWonderClass` actually, it does not depend on the `iBeginWonders` constant being set correctly.

2017-03-13 14:55 UTC, MeuhV1 commented
Done.

2017-03-13 15:20 UTC, dguenms approved these changes

2017-03-13 15:20 UTC, merged