Pedia texts updates
dguenms/Dawn-of-Civilization pull request #151
Opened 2017-04-12 15:25 UTC by MeuhV1

- Pedia texts for HR buildings
- Updated strategy texts for buildings and wonders
- Spanish Citadel provides culture like the vanilla Castle

2017-04-13 14:03 UTC, dguenms requested changes

2017-04-13 14:03 UTC, dguenms commented on Assets/Python/CvRFCEventHandler.py
> +			pCity.setBuildingCommerceChange(iEmpireStateBuilding, 0, iPop)
These won't work, `iEmpireStateBuilding` refers to the building, but the method requires the building class. The best we could do is `gc.getBuildingInfo(iEmpireStateBuilding).getBuildingClassType()`.

2017-04-13 14:03 UTC, dguenms commented on Assets/Python/CvRFCEventHandler.py
> +			city.setBuildingCommerceChange(iEmpireStateBuilding, 0, iPop)
See above.

2017-04-13 14:03 UTC, dguenms commented on Assets/Python/CvRFCEventHandler.py
> +			city.setBuildingCommerceChange(iMachuPicchu, 0, iNumPeaks * 2)
See above.

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Buildings/CIV4BuildingInfos.xml
> +			<ObsoleteSafeCommerceChanges>
👍

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/National Wonders.xml
> +		<English>[COLOR_BUILDING_TEXT]Musea[COLOR_REVERT] greatle increase a city's cultural output. They also increase a city's [COLOR_HIGHLIGHT_TEXT]Great Person[COLOR_REVERT] birth rate depending on the
greatly

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/National Wonders.xml
> +		<English>[COLOR_BUILDING_TEXT]Armouries[COLOR_REVERT] increase a city's military unit production and provide culture.</English>
I think now that it's called Armoury instead of Military Academy, the culture bonus doesn't make much sense now.

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/National Wonders.xml
> +		<English>The [COLOR_BUILDING_TEXT]Central Bank[COLOR_REVERT] doubles its city's production of wealth and increases its chances of generating a [COLOR_UNIT_TEXT]Great Merchant[COLOR_REVERT].</Englis
I would say "doubles its city's wealth output" for consistency, and to avoid confusion with the "build wealth" action.

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>The [COLOR_BUILDING_TEXT]Reservoir[COLOR_REVERT], the Harappan replacement for the [COLOR_BUILDING_TEXT]Bath[COLOR_REVERT], doesn't require the [COLOR_TECH_TEXT]Medicine[COLOR_REVERT] tech
It's not intentional for Reservoirs and Baths to provide different culture.

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>[COLOR_BUILDING_TEXT]Harbors[COLOR_REVERT] improve the food output of water plots. A [COLOR_BUILDING_TEXT]Harbor[COLOR_REVERT] is required to build [COLOR_BUILDING_TEXT]Customs Houses[COLO
Wharfs (plural as with Custom Houses).

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>The [COLOR_BUILDING_TEXT]Candi[COLOR_REVERT], the Indonesian replacement for the [COLOR_BUILDING_TEXT]Pagan Temple[COLOR_REVERT], provides one production and never goes obsolete.</English>
Should be a Monument replacement now, is it not?

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>[COLOR_BUILDING_TEXT]Jails[COLOR_REVERT] lower city maintenance costs and increase espionage. They are required to build [COLOR_BUILDING_TEXT]Constabula[COLOR_REVERT].</English>
Constabularies

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>[COLOR_BUILDING_TEXT]Nuclear Plants[COLOR_REVERT] provide pollution-free power with access to [COLOR_HIGHLIGHT_TEXT]Uranium[COLOR_REVERT].</English>
You should also mention the scientist slot and the ability to build ICBMs.

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>[COLOR_BUILDING_TEXT]Laboratories[COLOR_REVERT] increase a city's scientific research and its spaceship production.</English>
It should be research with power, is it not?

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>Protestant Monastery</English>
It's still supposed to be a Seminary ...

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<French>Mosqu&#233;e</French>
Looks like there is an adjective missing here.

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>[COLOR_BUILDING_TEXT]Estates Towers[COLOR_REVERT] greatly increase a city's cultural output.</English>
Estates. Also no mention of artist/statesman slots?

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<French>Tracé à l'Italienne</French>
Looks like a unicode error here.

2017-04-13 14:03 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>[COLOR_BUILDING_TEXT]Electrical Grids[COLOR_REVERT] increase commerce output in cities with with access to power.</English>
Double "with".

2017-04-14 09:25 UTC, MeuhV1 commented
Updated comments.

Removed culture from Armoury. Added culture to the Harappan Reservoir so it matches the Bath.

2017-04-14 12:47 UTC, dguenms requested changes
Only two more.

2017-04-14 12:47 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<German>Islamische Gro&#223;moschee</German>
Now there is German twice.

2017-04-14 12:47 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>[COLOR_BUILDING_TEXT]Department Stores[COLOR_REVERT] increase wealth in cities with with access to power.</English>
"with with"

2017-04-14 13:54 UTC, MeuhV1 commented
Fixed

2017-04-14 17:03 UTC, dguenms approved these changes

2017-04-14 17:18 UTC, merged