Actual Specialist info (BUG) takes happiness changes into account
dguenms/Dawn-of-Civilization pull request #153
Opened 2017-04-21 11:33 UTC by MeuhV1

2017-04-21 13:09 UTC, dguenms requested changes
Great idea, I'll also look at it within the game before approving.

2017-04-21 13:09 UTC, dguenms commented on CvGameCoreDLL/CvGameTextMgr.cpp
> +				if (iHappinessChange > 0)
You can remove that `if` statement and collapse the two `setResumableValueChangeHelp` calls (see other examples that display happiness), something like `setResumableValueChangeHelp(szHelpString, szStart, L": ", L"", std::abs(iHappinessChange), iHappiness > 0 ? gDLL->getSymbolID(HAPPY_CHAR) : gDLL->getSymbolID(UNHAPPY_CHAR), false, true, bStarted)`

2017-04-21 21:32 UTC, MeuhV1 commented
New code, same change

2017-04-21 21:42 UTC, dguenms requested changes

2017-04-21 21:42 UTC, dguenms commented on CvGameCoreDLL/CvGameTextMgr.cpp
> +			bStarted = setResumableValueChangeHelp(szHelpString, szStart, L": ", L"", std::abs(iHappinessChange), iHappinessChange > 0 ? gDLL->getSymbolID(HAPPY_CHAR) : gDLL->getSymbolID(UNHAPPY_CHAR), false,
You still need the `iHappiness != 0` check though.

2017-04-21 22:10 UTC, MeuhV1 commented on CvGameCoreDLL/CvGameTextMgr.cpp
> +			bStarted = setResumableValueChangeHelp(szHelpString, szStart, L": ", L"", std::abs(iHappinessChange), iHappinessChange > 0 ? gDLL->getSymbolID(HAPPY_CHAR) : gDLL->getSymbolID(UNHAPPY_CHAR), false,
I did a check and there already is such a check in the setResumableValueChangeHelp function itself, so I left it out. Tested it and it works.

2017-04-25 12:16 UTC, dguenms commented on CvGameCoreDLL/CvGameTextMgr.cpp
> +			bStarted = setResumableValueChangeHelp(szHelpString, szStart, L": ", L"", std::abs(iHappinessChange), iHappinessChange > 0 ? gDLL->getSymbolID(HAPPY_CHAR) : gDLL->getSymbolID(UNHAPPY_CHAR), false,
Alright!

2017-04-25 12:16 UTC, merged