Code refactoring
dguenms/Dawn-of-Civilization pull request #192
Opened 2018-01-17 12:14 UTC by MeuhV1

Reversed looping over units. See the changes in plague.py for example

Rewrote the flipUnitsInCityBefore(), flipUnitsInCityAfter() and flipUnitsInArea() functions. It doesn't temporarily places units on (0, 67) anymore.

Deleted tTempFlippingCity from the StoredData. Temporarily saving the value is not needed.

2018-01-17 23:54 UTC, dguenms requested changes

2018-01-17 23:54 UTC, dguenms commented on Assets/Python/RFCUtils.py
> +							if unit.getUnitType() in [iWorker, iPunjabiWorker, iMadeireiro]:
Maybe an opportunity to use utils.getBaseUnit(), also should include the Labourer unit.

2018-01-18 12:28 UTC, MeuhV1 commented
Update the commit with your suggestion.

Included an isPossible() check in the 3rd Canadian UHV
Included a bugfix for the National Theatre. (Happpiness got increased when the building was removed, instead of decreased) This has a DLL update.
I rebased all files to the latest version just before I made the changes.

2018-01-21 21:36 UTC, MeuhV1 commented
Updated again to match the latest commit. (https://github.com/dguenms/Dawn-of-Civilization/commit/b93a5bf63de3af12bbc48716e46047f70acc5666)

Also did a minor update in CvScreenInterface.py

2018-01-23 22:52 UTC, dguenms approved these changes

2018-01-23 22:52 UTC, merged