Minor changes
dguenms/Dawn-of-Civilization pull request #194
Opened 2018-02-13 15:57 UTC by MeuhV1

Updated strategy texts
Fixed python exception in WB stability maps editor
Very minor code refactoring

2018-02-24 23:24 UTC, dguenms requested changes

2018-02-24 23:24 UTC, dguenms commented on Assets/Python/GreatPeople.py
> +def onGreatPersonBorn(unit, iPlayer, city, bWB = False):
Can you rename the new argument to something that is meaningful to the method itself? I would prefer something like `bAnnounceBirth = True`.

2018-02-25 14:00 UTC, MeuhV1 commented
Updated PR with your comment.

2018-02-25 14:02 UTC, dguenms approved these changes

2018-02-25 14:03 UTC, merged