Added language tags
dguenms/Dawn-of-Civilization pull request #211
Opened 2018-05-07 17:48 UTC by MeuhV1

2018-05-07 20:21 UTC, MeuhV1 commented
I replaced all "No Translation" texts with the English text. Only for non-pedia text entries.

I used a script to auto-replace everything. It should have replaced only the new tags I created in the first commit.

2018-05-08 21:22 UTC, MeuhV1 commented
Added translation for vanilla techs and quotes

2018-05-12 08:52 UTC, dguenms requested changes
Some English texts should have been used.

There is also an issue with texts starting with a capital E, seems like the regex did not capture those correctly. I only reviewed diffs small enough to show up, so you should probably do a search for "<English>E" and verify for the entire diff.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Arabia.xml
> +		<French>banya</French>
Looks like something went wrong here.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Arabia.xml
> +		<French>mirate of Delhi</French>
Here too.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Byzantium.xml
> +		<French>pirus</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Byzantium.xml
> +		<French>xarchate of Alexandria</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Byzantium.xml
> +		<French>xarchate of Ctesiphon</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Byzantium.xml
> +		<French>xarchate of Achaia</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Byzantium.xml
> +		<French>xarchate of Africa</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Byzantium.xml
> +		<French>xarchate of Parthia</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Byzantium.xml
> +		<French>xarchate of Ravenna</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Byzantium.xml
> +		<French>xarchate of Spania</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Carthage.xml
> +		<Italian>No Translation</Italian>
Should use English text.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_China.xml
> +		<German>No Translation</German>
Should use English text.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Colombia.xml
> +		<French>mpire of Gran Colombia</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Japan.xml
> +		<German>No Translation</German>
Should use English text.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Mexico.xml
> +		<German>No Translation</German>
Should use English text.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Moors.xml
> +		<French>ast Umayyad Caliphate</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Ottomans.xml
> +		<French>yalet of Mesopotamia</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Ottomans.xml
> +		<French>yalet of Syria</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Ottomans.xml
> +		<French>yalet of R&#251;m</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Ottomans.xml
> +		<French>yalet of Yedisan</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/DynamicNames/DynamicNames_Ottomans.xml
> +		<French>yalet of Aceh</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/External/AutoSave.xml
> +		<French>d Save</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/External/AutoSave.xml
> +		<French>xit Save</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/External/BUFFY.xml
> +		<Spanish>abled</Spanish>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/External/Event Signs.xml
> +		<French>vent Signs</French>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/External/Reminder.xml
> +		<Spanish>able Reminders [ALT + M]</Spanish>
.

2018-05-12 08:52 UTC, dguenms commented on Assets/XML/Text/External/Strategy Overlay.xml
> +		<Spanish>abled</Spanish>
.

2018-05-12 22:18 UTC, MeuhV1 commented
It seems that the auto replace function is a bit overeager. I will fix it.

2018-05-14 10:22 UTC, dguenms reviewed
There are still some comments open where the English text should be used.

2018-05-14 13:09 UTC, MeuhV1 commented
Replaced all "No translations" text with the English texts. (Except pedia texts, they still have the "No translation" text)

Merged all "translation" commits into 1 commit.

2018-05-23 22:11 UTC, dguenms approved these changes
If you remove the recent conflicts I can merge this.

2018-05-24 10:35 UTC, MeuhV1 commented
Done.

2018-05-24 22:47 UTC, merged