Pagan temples texts
dguenms/Dawn-of-Civilization pull request #212
Opened 2018-05-17 23:21 UTC by etiennefd

I noticed that the specific Pagan temples lacked strategy and pedia texts. That was a wonderful target for productive procrastination, so I wrote them.

2018-05-21 22:12 UTC, dguenms requested changes

2018-05-21 22:12 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<French>Le [COLOR_BUILDING_TEXT]Temple olympien[COLOR_REVERT] remplace le [COLOR_BUILDING_TEXT]Temple pa&#239;en[COLOR_REVERT] chez les civilisations adeptes du [COLOR_HIGHLIGHT_TEXT]Pesedjet[COLOR
Looks like a copy paste error.

2018-05-21 22:12 UTC, dguenms commented on Assets/XML/Text/Buildings.xml
> +		<English>The [COLOR_BUILDING_TEXT]Ziggurat[COLOR_REVERT] replaces the [COLOR_BUILDING_TEXT]Pagan Temple[COLOR_REVERT] for civilizations that follow [COLOR_HIGHLIGHT_TEXT]Anunnaki[COLOR_REVERT] and
I think I would prefer a formulation along the lines of "The Ziggurat is the Pagan Temple of civilizations that follow Anunnaki and ..."

2018-05-22 02:40 UTC, etiennefd commented
Your requests have been met. I also translated the pedia texts into French.

2018-05-23 21:57 UTC, dguenms approved these changes

2018-05-23 21:57 UTC, merged