Fixed two python errors
dguenms/Dawn-of-Civilization pull request #246
Opened 2018-10-05 09:19 UTC by MeuhV1

- Top Cities when there are less then 5 cities in the world
- Removed Atomium part of RFCEventHandler. The implementation is in CvCity::processBuilding() and CvPlayer::changeNumNukeUnits().

2018-10-05 21:12 UTC, dguenms requested changes

2018-10-05 21:12 UTC, dguenms commented on Assets/Python/Screens/CvInfoScreen.py
> +		for i in range(min(len(lCities), 5)):
I'd prefer
```
for i, city in enumerate(lCities):
```
here, followed by using the `city` object directly.

2018-10-05 21:12 UTC, dguenms commented on Assets/Python/CvRFCEventHandler.py
> -		# Leoreth: Atomium
True, I'm confused now why this is left over.

2018-10-06 08:31 UTC, MeuhV1 commented
Done

2018-10-06 12:45 UTC, dguenms approved these changes

2018-10-06 12:46 UTC, merged