Improved Great People 8
dguenms/Dawn-of-Civilization pull request #264
Opened 2019-02-03 16:01 UTC by etiennefd

The main change is that I split Holy Rome and Germany, and added many names to both. The split is from 18th century onwards, so all pre-1700 Germans are in the Holy Rome list, as are post-1700 people who are more closely associated with Austria (including a few Hungarians and Czechs). Post-1700 people who are more closely associated with Prussia or modern Germany are in the Germany list. 

Things are not always clear cut for 18th c. people who were not Prussian or Austrian (Schiller? Goethe?). One possibility would be to make the split only from the industrial era onwards. Let me know. I don't claim any sort of particular knowledge of German culture and history, so I might have made some questionable choices. One thing I'm sure of is that Gutenberg and Kafka really needed to be added to the list. 

Other changes:
- Ethiopia: removed Ezana and Menelik, added Haile Selassie as a prophet.
- Added Publicola's suggestions for Mongolian GPs.
- Moved the Maya and China to preserve spawn order.
- Various other additions and corrections.

2019-02-03 16:57 UTC, dguenms commented
Haven't looked into the changes in depth, but a possible solution for the neither Prussian nor Austrian GPs is to just include them in both lists. The game will still consider an already used name taken and not spawn them for the other civ.

2019-02-03 17:11 UTC, etiennefd commented
That's probably a good idea. I'll go over the lists and change them accordingly. 

> Le 3 févr. 2019 à 11:57, Daniel Günther <notifications@github.com> a écrit :
> 
> Haven't looked into the changes in depth, but a possible solution for the neither Prussian nor Austrian GPs is to just include them in both lists. The game will still consider an already used name taken and not spawn them for the other civ.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/dguenms/Dawn-of-Civilization/pull/264#issuecomment-460068368>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AGGQG7gwj8m65ganwI4P_mtylzPrhyK4ks5vJxTggaJpZM4agLLv>.
>

2019-02-04 13:15 UTC, dguenms requested changes

2019-02-04 13:15 UTC, dguenms commented on Assets/Python/GreatPeople.py
> +		"Damdin Sükhbaatar", # 20th
u""

2019-02-04 13:15 UTC, dguenms commented on Assets/Python/GreatPeople.py
> +		"fHildegard von Bingen", # 12th
Hildegard von Bingen should stay a prophet imo

2019-03-07 23:23 UTC, dguenms approved these changes

2019-03-07 23:23 UTC, merged