Korean GP names update
dguenms/Dawn-of-Civilization pull request #281
Opened 2019-04-29 04:19 UTC by mbird1205

Deleted a couple of people with somewhat little historical impact.
Added some important historic figures.
Category change for some names.
Fixed spelling for some names.

2019-04-29 21:01 UTC, dguenms requested changes

2019-04-29 21:01 UTC, dguenms commented on Assets/Python/GreatPeople.py
> -		"Kim Ok-gyun", # 19th
Wikipedia transliterates Korean names as capital letters only at the beginning of the name, not after the hyphen. Let's stick to that.

2019-04-29 21:01 UTC, dguenms commented on Assets/Python/GreatPeople.py
> +		"GyeBaek", # 7th
Gyebaek

2019-04-30 05:49 UTC, mbird1205 commented on Assets/Python/GreatPeople.py
> -		"Kim Ok-gyun", # 19th
OK

2019-04-30 05:49 UTC, mbird1205 commented on Assets/Python/GreatPeople.py
> +		"GyeBaek", # 7th
OK

2019-04-30 05:54 UTC, closed without merging