Korean GP names update - with fixes
dguenms/Dawn-of-Civilization pull request #284
Opened 2019-04-30 05:54 UTC by mbird1205

Small letters after hyphens. e.g. Ok-Gyun -> Ok-gyun
GyeBaek -> Gyebaek.

2019-04-30 05:56 UTC, mbird1205 commented
Closed the first PR because I made a new branch with the fix.
Sorry if this causes confusion, I'm not too familiar with Github.

2019-04-30 13:35 UTC, dguenms requested changes

2019-04-30 13:35 UTC, dguenms commented on Assets/Python/GreatPeople.py
> +		"Moon Sun-Myung", # 20th
Lower case.

2019-04-30 13:35 UTC, dguenms commented on Assets/Python/GreatPeople.py
> +		"Kim Su-Hwan", #20th
Lower case.

2019-04-30 13:35 UTC, dguenms commented on Assets/Python/GreatPeople.py
> +		"Che Je-Gong", # 18th
Lower case.

2019-05-01 04:38 UTC, mbird1205 commented
Fixed.

2019-05-02 14:47 UTC, dguenms approved these changes

2019-05-02 14:47 UTC, merged