German translation for War Chariot Strategy and Desert Adaptation Promotion
dguenms/Dawn-of-Civilization pull request #301
Opened 2019-06-27 06:28 UTC by Imperator-Knoedel

2019-06-27 17:12 UTC, dguenms commented
Why are so many commits in this PR? It should only be the last one.

2019-06-27 17:13 UTC, dguenms requested changes

2019-06-27 17:13 UTC, dguenms commented on Assets/XML/Text/Promotions.xml
> +		<German>W&#252;sten Anpassung</German>
That's a deppenleerzeichen. Please use Wüsten-Anpassung or Wüstenanpassung

2019-06-28 18:34 UTC, Imperator-Knoedel commented
> Why are so many commits in this PR? It should only be the last one.

That's a good question, I'll look into it.

2020-02-18 14:15 UTC, closed without merging